### ISSUE TITLE
In the overview, add a "forget to log out" column. 

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#12]
With an angry smilie if they forgot to check out once that week 😡 
And a happy smile if everything is fine 🙃

**Comment by AhmedBHameed** [comment]
It is possible to implement that but as you notice that the row is so big because we have a huge amount of data. so the question are you sure that you need to add this column?
Another thing that we have to discover a new way of showing those data in a nice dynamic way that can be controlled by screen size (tablet, mobile, desktop).

**Comment by AhmedBHameed** [comment]
It is possible to implement that but as you notice that the row is so big because we have a huge amount of data. so the question are you sure that you need to add this column?
Another thing that we have to discover a new way of showing those data in a nice dynamic way that can be controlled by screen size (tablet, mobile, desktop).
