### ISSUE TITLE
Some Errors after the update..

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#15]
When logged in as an admin, in the participants panel, I cannot update users anymore. The Fields will no longer be pre-loaded, and even if I fill them, this error shows up:

Errer
could not execute statement; SQL [n/a]; constraint [uk_fwmwi44u55bo4rvwsv0cln012]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by AhmedBHameed** [comment]
Hmmm, i see there are some bugy things.

**Comment by darioseidl** [comment]
Hi, some of the errors may already be fixed. We didn't redeploy the frontend after the hackathon. @AhmedBHameed is it ready to deploy?

**Comment by AhmedBHameed** [comment]
@AlexHartveld @darioseidl
The problem occur because of a single random user that has a value of null.
PLEASE If you want to use the system correctly then we have to secure the registration (NEW PARTICIPANT REGISTRATION).
The system right now acts like a toy that can be broken with any unknown rule set from the user.

** This is a basic rule in programming **
Plan --> Study scenarios and possibilities --> Then program your plan

We are here missing the second phases.

Otherwise it is just playing around.

**Comment by AhmedBHameed** [comment]
@darioseidl 
I thing not we have to work on some issue related with data. i have a user with duration value of null which caused a lot of troubles with the code

@AlexHartveld 
BTW guys the project is kind of getting bigger and we need to do some (study scenarios) before going further. Any change with the data at lest should be considered as a save change because it can effect other features.

One thing that i insist to do it is to secure the new participant registration which reduce our bugs and also reduce the garbage data inside our database.
