### ISSUE TITLE
New bug: enabling a new user leads to an error

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#16]
Error!
Request method 'POST' not supported

**Comment by AhmedBHameed** [comment]
@AlexHartveld @darioseidl 
The problem occur because of a single random user that has a value of null.
PLEASE If you want to use the system correctly then we have to secure the registration (NEW PARTICIPANT REGISTRATION).
The system right now acts like a toy that can be broken with any unknown rule set from the user.

** This is a basic rule in programming **
Plan --> Study scenarios and possibilities --> Then program your plan

We are here missing the second phases.

Otherwise it is just playing around.
